### PR TITLE
For instructional purposes, it's becoming useful to actually have buffered I/O

### PR DESCRIPTION
**Pull request by jordanhubbard**
I'm doing some forth training, and it's proving useful to be able to cut and paste (with echoing) examples into a forth session.  Without buffering, I cannot paste interactively, and nl does not display the characters it receives.  It's just not as seamless an experience.   I have conditionalized the code and also turned it off by default, so it's only something one would compile in for interactive demos.

### CODE REVIEW

**Comment by quozl** [comment]
This is a bit of a puzzle.  What buffer sizes worked for you?

`consoleio.c` implements a cloned UART and USB serial interface; when transmitting a byte, we wait for UART to be ready, drop the byte into transmit register, then put the byte into USB serial.

```c
void tx(char c)
{
  while(!(UART0_S1 & UART_S1_TDRE)) // pause until transmit data register empty
    ;
  UART0_D = c;
  if (seen_usb) {
    usb_serial_putchar(c);
    sent_usb++;
  }
}
```

Symptom of a long paste hang is that the first eight characters of the response are printed on `screen(1)`, then there is a long delay of half a minute or more, then the rest of the response may be printed.  At the time of the hang, the UART output is _one character ahead_ of the USB serial output, which suggests the code is hung within `consoleio.c:tx()`.  Might be proven with a GPIO twiddle.

Theory; the 70msec timeout expired.   Busted; raising `usb_serial.c:TX_TIMEOUT_MSEC` to 940msec makes no difference.

Theory; USB buffers depleted, waiting for one to be free.  Raising `usb_desc.h:NUM_USB_BUFFERS` by a factor of three increases the size of successful paste by the same factor.  Confirmed.

So an easier fix is to change `NUM_USB_BUFFERS`, but it still is not clear why we run out of USB buffers.  Might have something to do with how output is flushed when input is checked.

Effectively, your patch is freeing USB buffers by calling `usb_serial_getchar` more frequently?

What's the `EXTRA_CLEAN` change for?

**Comment by quozl** [comment]
I've enabled tracing in `usb_malloc` and `usb_free` and proven the pasted data consumes all buffers and there are none available for outgoing data.

I've tested changed `usb_malloc` to take an urgency argument, to report no buffers available to the pasted data path yet reserve one for the outgoing data, and this works somewhat better.  Interaction during a paste is less bursty.

While changing `usb_malloc` references, in [`usb_dev.c`](https://github.com/quozl/cforth-1/blob/arm-teensy3/src/platform/arm-teensy3/usb_dev.c#L1007) was discovered this;
```c
// TODO: implement a per-endpoint maximum # of allocated
// packets, so a flood of incoming data on 1 endpoint
// doesn't starve the others if the user isn't reading
// it regularly
```

So it looks like Paul knows about this already.

**Comment by jordanhubbard** [comment]
Interesting.  Let me answer the questions in order:

1. I tested with buffer sizes of 128 and 256 with good success, though 256 bytes allows larger multi-line pastes to go through without trouble so I ultimately picked that value (I also stuck with power-of-two sizes for obvious reasons; the allocation is more easily aligned by the compiler).

2. I don't actually see the "bursty" behavior you describe on my Mac, what I see instead is a fairly random set of characters echo'd, and occasionally characters even lost.  Let's take the following paste buffer contents:

 : star  
   #42 emit ;              

 : stars        
   0 do star loop ;

Now I paste it in with the 256 byte buffering enabled:

ok  : star  
 ]    #42 emit ;              
ok 
ok  : stars        
 ]    0 do star loop ;        

10 stars
`****************`

As you can see, it works and displays fine.  Now, the same paste with the buffering disabled:

ok  42 emit ;              
ok ok 
ok ok  : stars        
 ]  ]    0 do star loop ;        

ok 10 stars
`****************`
 ] ;

The interpreter hangs for about 10 seconds after this paste, and as you can see, once done it's echoing pretty fragmented parts of the paste.  Even worse, we can see that the last ; was dropped from the stars definition because I had to enter it as a continuation character after calling `10 stars`, so the paste was lossy as well as a bad User Experience.

3. The EXTRA_CLEAN change was because the arm-none-eabi compiler toolchain on the Mac, at least, leaves quite a few extra files behind.  To wit:

jkh@katana-> make clean
jkh@katana-> ls
Makefile	main.map	tdate.c
app.hex		makebi.dSYM	version

The makebi.dSYM file is the detached symbols directory and you can't add a directory to CLEAN_FILES so I left it out, but the others at least should be cleaned as they are intermediate build products.

**Comment by quozl** [comment]
Excellent data, thanks.  I'll take another look at what is happening.
I've not yet seen data loss with a Linux host.

Does the symptom still occur with larger pastes?

**Comment by jordanhubbard** [comment]
Yes, the symptom still occurs with larger pastes, though oddly enough it seems to sort of "fix itself" after a certain number of garbled characters.   For example, with this paste buffer:

variable foo1
variable foo2
variable foo3
variable foo4
variable foo5
variable foo6
variable foo7
variable foo8
variable foo9
variable fooA
variable fooB
variable fooC
variable fooD
variable fooE
variable fooF

I get this behavior, non-buffered:

ok vari2
ok variable foo3
ok variable foo4
ok variable foo5
ok variable foo6
ok variable foo7
ok variable foo8
ok variable foo9
ok variable fooA
ok variable fooB
ok variable fooC
ok variable fooD
ok variable fooE
ok variable fooF

As you can see, the first two lines got pretty mangled (the first line being dropped entirely) but then once it finished mangling them, it "recovered" inasmuch as subsequent lines are fine (after about a 10 second delay).  One might have expected it to start dropping characters again later in the paste.

With the 256 byte buffer, of course, this problem goes away entirely.

**Comment by quozl** [comment]
Was that an output packet loss?  Test with `see foo1` and `see foo2`; if they are defined then what you've lost is the output packets.  Buffer exhaustion is on the output packets in my tests.  Increasing `NUM_USB_BUFFERS` is very effective.  Paul's USB code prioritises input packets at the cost of losing output packets, and applies flow control through to the host as soon as all buffers are allocated.  In that state we deadlock, because we can't allocate a buffer for transmit data.

**Comment by quozl** [comment]
Okay, please try 66b742e2d094bd3e9313315126597e3b32384a95 on branch arm-teensy3-pr-2 without your 256 byte buffer.

66b742e2d094bd3e9313315126597e3b32384a95 prevents USB transmit buffer exhaustion by splitting the buffer pool 50/50 between transmit and receive paths.  Flow control is now enforced through to the host, because the USB controller on the Teensy isn't given a buffer for receive until one is available from the half of the pool used for receive.

In my interactive tests it handles 128 line pastes, and I'm starting to hit the limits of `screen(1)`.  By running `cat /dev/ttyACM0` in one terminal, and `cat file > /dev/ttyACM0` in another terminal, it easily handles 2000 line pastes.

Note that UART output is turned off for the moment; so the USB transmit path is as fast as it can be, rather than slowed to 115200 baud of UART.  I've tried with and without UART output, no issues.

**Comment by jordanhubbard** [comment]
Hmmm.  Odd!   When I check out  66b742e and build it (from clean sources), my teensy 3.2's output is basically broken.  To wit:

 ok words
{ 
ok

**Comment by quozl** [comment]
Thanks, cause was missing `ccalls` stack effect for `bye` which resulted in the `ccalls` vocabulary remaining active. which only has `{`; workaround is to type `forth` first.  Regression introduced in https://github.com/quozl/cforth-1/commit/702efdca4b3287f373a9c78d6e364af190cb371c#diff-a97e00639f9ab5818ef606516772839cR51

Please test 2b7f82142d78a94d8bef87fd025f4b337a4a3bc9 instead.

**Comment by jordanhubbard** [comment]
Yep, that's done the trick!  Nice - proper interpreter behavior with no input buffering!

**Comment by quozl** [comment]
Thanks.  Actually, it has buffering, in the USB driver, but unlike before the buffering is fairly shared between TX and RX paths.  I'll clean it up, rebase the patches and push to `arm-teensy3` branch.

**Comment by quozl** [comment]
https://github.com/quozl/cforth-1/commit/3bcb753a63cecf032a09cc6b92bc090c82ce56be

**Comment by jordanhubbard** [comment]
How about the EXTRA_CLEAN additions; you want those in a separate PR?

**Comment by quozl** [comment]
Good point.  Moved the file names to the makefile that caused them.  See 53d804366ca026d50f0df3deadd7f4d29692f9d6.

**Comment by quozl** [comment]
https://github.com/MitchBradley/cforth/pull/25 upstreamed.

**Pull request closed without merging**
